### ISSUE TITLE
segment-region: crop_polygons creates invalid coordinates

### ISSUE THREAD

**Issue by bertsky** [OCR-D/ocrd_tesserocr#98]
When using `ocrd-tesserocr-segment-region` with `crop_polygons=True`, one will frequently get coordinates extending the segment bbox, which could easily end up in negative coordinates (which is forbidden syntactically in PAGE-XML). 

So maybe Tesseract's [BlockPolygon](https://github.com/tesseract-ocr/tesseract/blob/420cbac876b06beeee271d9f44ba800d943a8a83/src/ccmain/pageiterator.cpp#L378) must be clipped just like its [BoundingBox](https://github.com/tesseract-ocr/tesseract/blob/420cbac876b06beeee271d9f44ba800d943a8a83/src/ccmain/pageiterator.cpp#L331) is clipped?

**Comment by bertsky** [comment]
Also, this parameter should be called just `polygons` (because it is independent of how cropping is done now).

**Comment by wrznr** [comment]
I'd even say the parameter should be called bboxes as soon as this issue is fixed. Polygons should be the default.

**Comment by bertsky** [comment]
> Polygons should be the default.

I agree, but we still have the issue of Tesseract generating invalid (self-intersecting) polygon paths internally, which end up in very strange ways on the consumer side (depending on how the coordinates are being processed, with numpy / skimage / cv2 etc). But maybe it's enough to check against that as well – using `Shapely`, and as a workaround, taking the `exterior` or the self-union...

**Comment by stweil** [comment]
The `tesseract` command line executable also has an [issue with an endless loop](https://github.com/tesseract-ocr/tesseract/issues/2288) when doing segmentation for certain images.

I did not test whether this affects ocrd_tesserocr, too.

**Comment by bertsky** [comment]
Strangely, this affects only image, line and table regions (but not always) – never text regions.

**Comment by bertsky** [comment]
This appears to affect all kinds of regions, but only when they have been rotated internally. Anyway, this is _not_ about clipping to the image/rectangle.

**Comment by bertsky** [comment]
We now have a partial solution in [Tesseract itself](https://github.com/tesseract-ocr/tesseract/pull/2826), but on top of that I still hesitate to make a PR for the convex_hull workaround here...

**Comment by bertsky** [comment]
What if instead of trying to find the bug deep inside Tesseract's polyblk generator we take the liberty of annotating text regions _along with text lines_ in one pass? (Perhaps even with #127 ...)
